-- Decompiled with Potassium's decompiler.

local v1 = {
    MAX_DURATION = 5,
    DEPLOY_DELAY = 0.5,
    MOUSE_RANGE = 100,
    THROW_TIME = 0.25,
    UMBRELLA_FORWARD = 16,
    UMBRELLA_HEIGHT = 3,
    DEPLOY_RANGE = 25,
    DEPLOY_BACK = 3
};
v1.DEPLOY_HITBOX_SIZE = Vector3.new(12, 12, v1.DEPLOY_RANGE + v1.DEPLOY_BACK);
v1.DEPLOY_HITBOX_OFFSET = CFrame.new(0, v1.UMBRELLA_HEIGHT, -(v1.DEPLOY_RANGE - v1.DEPLOY_BACK) / 2);
v1.BARRAGE_INTERVAL = 0.3;
v1.DEPLOY_KNOCKBACK = 4;
v1.DEPLOY_DAMAGE = 2;
v1.DEPLOY_STRICT_STUN = 1;
v1.DEPLOY_KNOCKBACK_DURATION = v1.DEPLOY_STRICT_STUN;
v1.DEPLOY_BLOCK_BREAK = 0.25;
v1.RETURN_TIME = 0.3;
v1.PULL_FRONT_DIST = 4;
v1.RELEASE_DURATION = 1.33;

return v1;