-- Decompiled with Potassium's decompiler.

return {
    AIM_RANGE = 45,
    BEAM_CURVE_HEIGHT = 35,
    START_ANIM_SPEED = 1.5,
    HOLD_FREEZE_AT = 0.25,
    HOLD_NR_DURATION = 6,
    DASH_SEGMENTS = 10,
    DASH_MAX_HANG_TIME = 0.5,
    DASH_RESPONSIVENESS = 165,
    DASH_MAX_FORCE = 30000,
    DASH_PAUSE_GAMEPLAY = 1.25,
    RELEASE_NR_DURATION = 1,
    SLAM_DAMAGE = 26,
    SLAM_STUN = 1.5,
    SLAM_RAGDOLL = 1.5,
    SLAM_BLOCK_BREAK = 3,
    SLAM_KNOCKBACK = 40,
    SLAM_KNOCKUP = 15,
    SLAM_HITBOX_SIZE = Vector3.new(27, 15, 25),
    SLAM_HITBOX_OFFSET = CFrame.new(0, -2, -7)
};