-- Decompiled with Potassium's decompiler.

return {
    HOLD_STARTUP_DUR = 0.4,
    RELEASE_LOCK_DURATION = 1.3,
    RELEASE_HIT_AT = 0.5,
    RELEASE_HITBOX_OFFSET = CFrame.new(0, -2, -18),
    RELEASE_HITBOX_SIZE = Vector3.new(24, 26, 44),
    RELEASE_DAMAGE = 28,
    RELEASE_STUN = 1.5,
    RELEASE_RAGDOLL = 1.5,
    RELEASE_BLOCK_BREAK = 3,
    RELEASE_KNOCKBACK = 50,
    RELEASE_KNOCKUP = 15,
    COUNTER_HIT_AT = 0.5,
    COUNTER_VICTIM_PAUSE = 0.6,
    COUNTER_DAMAGE = 20,
    COUNTER_STUN = 1.5,
    COUNTER_RAGDOLL = 1.5,
    COUNTER_KNOCKBACK = 50,
    COUNTER_KNOCKUP = 15
};