-- Decompiled with Potassium's decompiler.

local v1 = {
    RANGE = 53.6,
    BEAM_ARC_HEIGHT = 25,
    HOLD_FREEZE_AT = 0.15,
    HOLD_NR_DURATION = 6,
    TRAVEL_SEGMENTS = 10,
    MAX_TRAVEL_TIME = 0.625,
    TRAVEL_RESPONSIVENESS = 120,
    TRAVEL_MAX_FORCE = 30000,
    TRAVEL_LOCK_DURATION = 1.25,
    UNHOLD_NR_DURATION = 1,
    UNHOLD_CANCEL_WINDOW = 1,
    IMPACT_HITBOX_SIZE = Vector3.new(15.5, 25, 15.5),
    IMPACT_BLOCK_BREAK = 3,
    IMPACT_STUN = 1.85,
    ANIM_SPEED = 1
};
v1.ANIM_DURATION = 1.48 / v1.ANIM_SPEED;
v1.CUTSCENE_FOV = 50;
v1.THRUST_DAMAGE_AT = 0.117;
v1.THRUST_DAMAGE = 3;
v1.EXPLOSION_DELAY = 0.95;
v1.EXPLOSION_STUN = 1;
v1.EXPLOSION_DAMAGE = 18;
v1.SLOW_VALUE = "FlutteringStingSlow";
v1.SLOW_FACTOR = -0.3;
v1.SLOW_DURATION = 4;

return v1;