-- Decompiled with Potassium's decompiler.

return {
    MOUSE_RANGE = 500,
    STARTUP_DUR = 0.417,
    RELEASE_DELAY = 0.067,
    HITBOX_SIZE = Vector3.new(24, 24, 24),
    HITBOX_OFFSET = CFrame.new(0, 0, -3),
    BLOCK_BREAK = 5,
    BLOCK_KNOCKBACK = 30,
    BLOCK_KNOCKBACK_DUR = 0.1,
    CUTSCENE_DURATION = 6.833,
    CUTSCENE_FOV = 45,
    FINISHER_AT = 5.35,
    FINISHER_STUN = 1.5,
    FINISHER_RAGDOLL = 1.5,
    FINISHER_DAMAGE_DELAY = 0.5,
    FINISHER_DAMAGE = 60,
    POISON_TICK_DAMAGE = 1,
    POISON_DURATION = 5
};