-- Decompiled with Potassium's decompiler.

return {
    AIM_RADIUS = 80,
    HOLD_FREEZE_AT = 0.7,
    HOLD_UPDRAFT_HEIGHT = 25,
    HOLD_UPDRAFT_DUR = 5,
    CANCEL_WINDOW = 7,
    SHOOT_IMPACT_DELAY = 0.25,
    IMPACT_HITBOX_SIZE = Vector3.new(26, 15, 26),
    IMPACT_BLOCK_BREAK = 2.5,
    UNHOLD_RELEASE_DUR = 0.66,
    BITE_LOCK_DUR = 3.15,
    BITE_TICK_COUNT = 15,
    BITE_TOTAL_DUR = 2.675,
    BITE_HITBOX_SIZE = Vector3.new(26, 15, 26),
    BITE_TICK_DAMAGE = 0.5,
    BITE_STUN = 1.5,
    BITE_TICK_KNOCK_DUR = 0.5,
    BITE_BLOCK_BREAK = 0.2,
    FINAL_DAMAGE = 9,
    FINAL_RAGDOLL = 1.5,
    FINAL_KNOCKBACK = 35,
    FINAL_KNOCKBACK_SIDE = 15,
    FINAL_KNOCKBACK_DUR = 0.35
};