-- Decompiled with Potassium's decompiler.

local v1 = {
    AIM_RADIUS = 45,
    HOLD_SAFETY_DUR = 6,
    HOLD_FREEZE_AT = 0.2,
    UNHOLD_LOCK_DUR = 0.5,
    CANCEL_WINDOW = 1,
    TELEPORT_DUR = 0.16666666666666666,
    SLASH_HITBOX_OFFSET = CFrame.new(0, 0, -7),
    SLASH_HITBOX_SIZE = Vector3.new(16, 16, 22),
    SLASH_DAMAGE = 7,
    SLASH_STUN = 1.5,
    SLASH_BLOCK_BREAK = 3.5,
    IFRAME_DUR = 0.75,
    FOLLOWUP_AT = 0.25,
    FOLLOWUP_HIT_AT = 0.6,
    FOLLOWUP_DAMAGE = 14,
    FOLLOWUP_STUN = 1,
    FOLLOWUP_RAGDOLL = 1,
    FOLLOWUP_KNOCKBACK = 15,
    FOLLOWUP_KNOCKBACK_DUR = 0.15,
    FOLLOWUP_BLOCK_BREAK = 1,
    VENOM_DURATION = 4,
    VENOM_MAX_HEALTH_RATIO = 0.01
};
v1.CAST_LOCK_DUR = v1.UNHOLD_LOCK_DUR;
v1.FOLLOWUP_LOCK_DUR = v1.FOLLOWUP_AT + v1.FOLLOWUP_HIT_AT + 0.15;

return v1;