-- Decompiled with Potassium's decompiler.

return {
    AFTERGLOW_HITBOX_SIZE = Vector3.new(35, 35, 35),
    AFTERGLOW_FINAL_HITBOX_SIZE = Vector3.new(55, 55, 55),
    AFTERGLOW_DAMAGE = 3.2,
    AFTERGLOW_FINAL_DAMAGE = 22,
    AFTERGLOW_STUN = 0.45,
    AFTERGLOW_FINAL_STUN = 1.5,
    AFTERGLOW_FINAL_KNOCKBACK = 60,
    AFTERGLOW_CAST_LOCK = 4,
    AFTERGLOW_FINISH_LOCK = 0.93,
    AFTERGLOW_TICK_KNOCKBACK = 3,
    AFTERGLOW_TICK_UPWARD = 2,
    AFTERGLOW_FINAL_UPWARD = 15,
    AFTERGLOW_TICK_BLOCK_BREAK = 0.25,
    AFTERGLOW_FINAL_BLOCK_BREAK = 5
};