-- Decompiled with Potassium's decompiler.

return {
    MOUSE_RANGE = 80,
    DASH_STARTUP_DURATION = 0.75,
    DASH_SPEED = 65,
    DASH_START_ANIM_SPEED = 1.15,
    PROBE_START_AT = 0.1,
    FRONT_STOP_OFFSET = Vector3.new(0, 0, -9.5),
    FRONT_STOP_SIZE = Vector3.new(15, 6, 24),
    BARRAGE_HIT_COUNT = 12,
    BARRAGE_HITBOX_SIZE = Vector3.new(20, 12, 22),
    BARRAGE_FINISH_HITBOX_SIZE = Vector3.new(12, 12, 18),
    BARRAGE_DAMAGE = 1.5,
    BARRAGE_FINISH_DAMAGE = 10,
    BARRAGE_STUN = 0.35,
    BARRAGE_FINISH_STUN = 0.6,
    BARRAGE_KNOCKBACK = 4,
    BARRAGE_FINISH_KNOCKBACK = 60
};