-- Decompiled with Potassium's decompiler.

return {
    MOUSE_RANGE = 500,
    HOLD_FREEZE_AT = 0.2,
    MIN_HOLD_DUR = 0.19,
    RELEASE_LOCK_DURATION = 2,
    RELEASE_WAIT = 1.5,
    THROW_AT = 0.165,
    EXPLODE_DELAY = 0.36,
    LAUNCH_DELAY = 0.8,
    EXPLODE_HITBOX_OFFSET = CFrame.new(0, 0, -15.5),
    EXPLODE_HITBOX_SIZE = Vector3.new(27, 15, 32),
    EXPLODE_DAMAGE = 14,
    EXPLODE_STUN = 1,
    EXPLODE_KNOCKBACK = 2,
    EXPLODE_KNOCKUP = 5,
    EXPLODE_KNOCKBACK_DURATION = 1,
    EXPLODE_BLOCK_BREAK = 2,
    LAUNCH_HITBOX_SIZE = Vector3.new(32.4, 24, 38.4),
    LAUNCH_DAMAGE = 14,
    LAUNCH_STUN = 1.5,
    LAUNCH_RAGDOLL = 1.5,
    LAUNCH_KNOCKBACK = 40,
    LAUNCH_KNOCKUP = 30,
    LAUNCH_KNOCKBACK_DURATION = 0.3,
    LAUNCH_BLOCK_BREAK = 2
};