-- Decompiled with Potassium's decompiler.

return {
    MOUSE_RANGE = 500,
    DRIVE_SPEED = 9,
    MOVER_LIFETIME = 3,
    SLICE1_AT = 0.345,
    SLICE2_AT = 0.8,
    SPIN_AT = 1.33,
    SLICE3_AT = 1.7,
    SLICE1_HITBOX_OFFSET = CFrame.new(-3, 3, -7),
    SLICE1_HITBOX_SIZE = Vector3.new(10, 10, 20),
    SLICE2_HITBOX_OFFSET = CFrame.new(0, 3, -17),
    SLICE2_HITBOX_SIZE = Vector3.new(15, 10, 15),
    SPIN_HITBOX_OFFSET = CFrame.new(0, 3, -4),
    SPIN_HITBOX_SIZE = Vector3.new(30, 8, 30),
    SLICE3_HITBOX_OFFSET = CFrame.new(0, 3, -17),
    SLICE3_HITBOX_SIZE = Vector3.new(15, 10, 15),
    HIT_DAMAGE = 2.5,
    HIT_STUN = 1,
    HIT_KNOCKBACK = 15,
    HIT_KNOCKUP = 1,
    HIT_KNOCKBACK_DURATION = 0.4,
    HIT_BLOCK_BREAK = 0.5,
    HIT_BLOCK_KNOCKBACK = 25,
    FINAL_DAMAGE = 2.5,
    FINAL_STUN = 1,
    FINAL_RAGDOLL = 1,
    FINAL_KNOCKBACK = 35,
    FINAL_KNOCKBACK_DURATION = 0.25
};