-- Decompiled with Potassium's decompiler.

return {
    VERSION = "0.5.0",
    RESET_TRANSFORM_ON_SKIP = true,
    YIELD_ON_COLLIDER_GATHER = false,
    ALLOW_LIVE_GAME_DEBUG = false,
    FAR_PLANE = 500,
    FRUSTUM_FREQ = 2,
    LOG_VERBOSE = false,
    RESET_BONE_ON_DESTROY = true,
    STARTUP_PRINT_ENABLED = true,
    DEBUG_OVERLAY_ENABLED = false,
    DEBUG_OVERLAY_TREE = true,
    DEBUG_OVERLAY_TREE_INFO = false,
    DEBUG_OVERLAY_TREE_OBJECTS = false,
    DEBUG_OVERLAY_TREE_NUMERICS = false,
    DEBUG_OVERLAY_TREE_OFFSET = 0,
    DEBUG_OVERLAY_MAX_TREES = 5,
    DEBUG_OVERLAY_BONE = true,
    DEBUG_OVERLAY_BONE_OFFSET = 0,
    DEBUG_OVERLAY_MAX_BONES = -1,
    DEBUG_OVERLAY_BONE_INFO = false,
    DEBUG_OVERLAY_BONE_NUMERICS = false,
    DEBUG_OVERLAY_BONE_CONSTRAIN = false,
    DEBUG_OVERLAY_BONE_WELD = true,
    DEBUG_OVERLAY_BONE_FORCES = true
};